### ISSUE TITLE
Availability on fdroid?

### ISSUE THREAD

**Issue by ayoahha** [Alex313031/Thorium-Android#11]
Hi the team
Love the browser... Very good job !

Is there a plan to add a fdroid repo or any Android repo able to be contacted by fdroid/izzyondroid/droidify etc. ?
Thanks a lot

**Comment by gz83** [comment]
Thank you for your suggestion. It will be decided by Alex whether to submit Thorium to third-party app stores such as fdroid.

@ayoahha

**Comment by ghost** [comment]
I hope you add it to fdroid. First, It will be much easier for users to update. Second, fdroid users needs a good browser after bromite death. Third, fdroid build the app themselves and check for security venerabilities and for non free libs, so users can trust thorium much more.
It's a convenient way to install and update apps

**Comment by Ryhon0** [comment]
I'd prefer if it was added to a repository that's not fdroid because fdroid requires all packages be built by the fdroid team and this could lead to the app being behind on updates on fdroid

**Comment by ayoahha** [comment]
I'm sorry i didn'i see that a discussion has been created on that... Maybe we can switch to this disussion
No ?

See https://github.com/Alex313031/Thorium-Android/discussions/5
