### ISSUE TITLE
Custom Search Engine

### ISSUE THREAD

**Issue by LordZeuss** [Alex313031/Thorium-Android#14]
I know we can change the search engine, but for selfhosted guys like me, I run my own search engine. 

To be fair, I mainly use firefox and I am really interested in this project. Having this ability would be great, as I won't use open search engines. This feature, plus extensions (I know there is another request for that) would make this my android browser of choice.

Great project!

**Comment by gz83** [comment]
Thanks for the suggestion.

@LordZeuss

**Comment by lightningquick** [comment]
Yup. I would totally use Thorium on Android. It works so much better. 
Just need the option to add my own search engine. I also self host it.

**Comment by squidds** [comment]
What search application are you using @LordZeuss? Both SearXNG and Whoogle show up fine as selections in Thorium options after I did one search. I removed the URLs of my instances from the screenshot I'm posting. 
![Screenshot_20231025-131759_Thorium~2](https://github.com/Alex313031/Thorium-Android/assets/64927214/f97813f2-ae86-4fd9-90f3-0e2a3331efc1)

**Comment by squidds** [comment]
When you say open search engine, do you mean that whatever you're using does not comply with the search standard that chromium uses to detect an engine?

**Comment by LordZeuss** [comment]
> When you say open search engine, do you mean that whatever you're using does not comply with the search standard that chromium uses to detect an engine? 

No. I must have been doing it wrong. I went to my search engine (whoogle), did a search, and now it does indeed give me that as an option. 

I'm not sure if this is how it works with chromium, or if that is app specific. It would be nice to manually add it instead of doing it this way, but Thorium does support it, so I will close this issue as resolved. Thanks for this! It both solved my problem and now there may not be a need for dev time to do this.

**Comment by squidds** [comment]
This is a Chromium function. It's the same as on desktop. Mobile chromium browsers have the "index other search engines" enabled by default, and on desktop you need to select it under search settings. I believe thorium has it enabled by default on desktop too. Thorium on Android has this function working very well, this is one of my main reasons for leaving Brave as it does not always index the engine, and as stated earlier there is no option to manually add. An actual custom search function would probably be difficult for the thorium dev to add so I would not expect it.
