### ISSUE TITLE
Third party download manager support

### ISSUE THREAD

**Issue by ghost** [Alex313031/Thorium-Android#18]
Not always the built-in downloader is preferable in android, for example while downloading a big file(we need multiple threads). Yes we can just copy paste the link, but having an option just to redirect all the downloads to another app would be more convenient.

If there would be an option to choose a third party download manager like firefox and kiwi browser have, it would be amazing. Coz most of the modern browsers miss this feature.

**Comment by gz83** [comment]
thanks for your advice

**Comment by dhrubo66** [comment]
Upvoting this request for all the same reasons.
