### ISSUE TITLE
[Feature request] Option to move the toolbar to the botom

### ISSUE THREAD

**Issue by Brian5647** [Alex313031/Thorium-Android#19]
**Is your feature request related to a problem? Please describe.**

Other search engines support the option tot move the toolbar to the bottom of the screen on Android. Either i am blind or this functionality is not available in Thorium.

**Describe the solution you'd like, including relevant patches or source**

Some other browsers offer the option to move the toolbar to the bottom in order to make it more reachable on large phones. I would like to see a option in the settings menu to move it from the top to the bottom

I added a screenshot to maybe give you a better idea of what I mean.

![IMG_20231023_182712](https://github.com/Alex313031/Thorium-Android/assets/121485743/0ed8ae64-4934-4e4f-b4b8-761134bdfadc)
#

**Additional Notes**

**Comment by TakiShiwa** [comment]
Much awaited feature
