### ISSUE TITLE
Sync not working on Android 13

### ISSUE THREAD

**Issue by alfonsokuen** [Alex313031/Thorium-Android#21]
**System Details**
 - samsung zfold 4 android 13 
 - Thorium Version [M117.0.5938.157 - 3rd Release]
**Problem**
not log in on google account for sync.

**Screenshots**

**Additional Notes**

**Comment by TakiShiwa** [comment]
It's just saying add an account, but we already logged into a Google account, and it's not possible to add it one more time

**Comment by gz83** [comment]
Mark as duplicate
