### ISSUE TITLE
[ Feature Request ]  Adding custom filter support

### ISSUE THREAD

**Issue by ghost** [Alex313031/Thorium-Android#24]
Blocking ads is easy in desktop version where we can use extensions, but if there'd be a option like brave has, brave://adblock in Android versions and desktop versions also, where we can import any filter lists, e.g., easylist, that would suffice the adblocking need.                                                                            
                        
But if you guys are planning to add extension support then this can be ignored fairly.

Thank you for this amazing project

**Comment by gz83** [comment]
#12

**Comment by Candlemass** [comment]
I would prefer proper extension support but filter list support would at least be a consolation. This is the bare minimum I need in order to make the switch on android.
