### ISSUE TITLE
Can't Use Google Account Sync in Application

### ISSUE THREAD

**Issue by MagicalDemon** [Alex313031/Thorium-Android#26]
**System Details**
 - OS: Android 11
 - Thorium Version: Latest Version

**Problem**
When I click "turn on sync" on a fresh install, I don't see the any google accounts that I'm logged into on my Android Device... If I click add account and add a new google account it doesn't sign in & sync.

**Additional Notes**
There is no simpler problem with chrome.

Thank You In Advance 😄
Oct 31, 2023

**Comment by gz83** [comment]
#6
