### ISSUE TITLE
Can't sign into google 

### ISSUE THREAD

**Issue by ghostranger047** [Alex313031/Thorium-Android#27]
**System Details**
 - OS: Android 14
 - Thorium Version: 117(latest)

**Problem**
While trying to singn into google account, it asks to add a new account (unlike in other apps where the option is given from already present google account). And while trying to add the account it says account already exists.

**Screenshots**
![Screenshot_20231101-230558~2](https://github.com/Alex313031/Thorium-Android/assets/26534772/7d8e8589-fdb6-458d-a84d-6507df8c8d34)

**Comment by SadibSarwar2003** [comment]
Same issue on my phone. Android 13,

**Comment by Bonnyd825** [comment]
Same here, I wanted to use this browser along with sync of chrome autofill data/passwords. But unable to add Google account
