### ISSUE TITLE
Make support for ARM7 no NEON (tegra2 CPU)

### ISSUE THREAD

**Issue by Stepman123** [Alex313031/Thorium-Android#3]
Please do it for old CPU.

**Comment by Alex313031** [comment]
@Stepman123 This is no longer supported in Chromium. I could try to do it, but no promises.

**Comment by Stepman123** [comment]
@Alex313031 
There used to be a man who made buildings based on Bromite. https://github.com/Decatf/chromium_src/
Later, another person made Kiwi 77 on these instructions and it worked great. And then someone else made Chromium and WebView 96, but it has some problems with MP4.
