### ISSUE TITLE
Android - Clearify download options

### ISSUE THREAD

**Issue by ShalokShalom** [Alex313031/Thorium-Android#39]
Currently, there is no explaination of "SystemWebView" "Public" and "Shell" and the vast majority of Android users do not know, that "ARM64" is related to their phones. 

Its extremely unclear now to them (and even to me) which APK one should download. 

I also suggest to make the browser available on F-Droid.

**Comment by Alex313031** [comment]
@ShalokShalom  OK, I will make a doc explaining this and what to download.

**Comment by ShalokShalom** [comment]
I guess it would make sense, to add this to the release description (and to close, when its completed)

**Comment by elig0n** [comment]
was this ever done?

**Comment by ruin1990** [comment]
I found it with release note:

> Remember, Thorium_Public is the main browser, Thorium_Shell is a "mini browser", and SystemWebView should only be used by people who know what that is and how to use it.

> Lastly, people were confused about what to download. In general, you should download the "arm64" versions of things. The arm32 versions are only for very old devices with 32 bit CPUs. The main browser is "Thorium_Public", and the "Thorium_Shell" can be thought of as a "mini browser". The system web view should only be installed by people who are familiar with what that is and if their phone's OS will allow them to change the system webview from the default Google one to the Thorium compiler optimized one.
