### ISSUE TITLE
Crop logo icon

### ISSUE THREAD

**Issue by rabaimor** [Alex313031/Thorium-Android#40]
The icon appears way smaller because its not cutout. It would look way better if it was done like chrome, or other chromium browsers.

**Comment by rabaimor** [comment]
![Screenshot_20240118-235606](https://github.com/Alex313031/Thorium-Android/assets/74060134/0cba6319-f245-4756-9ee5-01e9b8ac8317)
Here is an example of the logo difference to an other chrome

**Comment by Alex313031** [comment]
@rabaimor This should be fixed in the upcoming M120 version.
