### ISSUE TITLE
[Feat] Add ads and trackers blocking or extentions

### ISSUE THREAD

**Issue by idontveapc** [Alex313031/Thorium-Android#46]
**Is your feature request related to a problem? Please describe.**
Not specifically, but would make it better than Chrome.

**Describe the solution you'd like, including relevant patches or source**
Adding a supported network op where fliterlists block domains that track or load ads, or and extension!!?

**Additional Notes**
There already existing Chromium browser with this feature except they aren't that similar. Some give editting-control of filterlists others don't, though an extension might let you choose.

**Comment by gz83** [comment]
duplicate

**Comment by idontveapc** [comment]
millions must demand
