### ISSUE TITLE
Thorium's SystemWebView has a lower score than Google Play's SystemWebView

### ISSUE THREAD

**Issue by psychosispy** [Alex313031/Thorium-Android#50]
For speedometer testing, Thorium's windows version runs well on my device, outperforming Chrome by 15%. However, the Android SystemWebView version is 30% slower than the SystemWebView updated via Google Play, and the Public.apk is 10% slower. 
The complete ranking is 
Google Play's SystemWebView with browsers based on 110
Public.apk 97
chrome 86
Thorium's SystemWebView and browsers based on it 77

This could be related to Google Play's WebView utilizing the TrichromeLibrary and apks encapsulation? expect your optimization for Thorium's SystemWebView,thanks

**Comment by brian6932** [comment]
It's likely due to the fact that there's no up to date Thorium aarch64 WebView distributed bin. A few older versions in `/releases` have it.

**Comment by psychosispy** [comment]
> It's likely due to the fact that there's no up to date Thorium aarch64 WebView distributed bin. A few older versions in `/releases` have it.

The version I'm testing is m120, 64-bit, but it defaults to using 32-bit libraries on my device. This seems to be a bug   
primaryCpuAbi="armeabi-v7a"
secondaryCpuAbi="arm64-v8a"

**Comment by psychosispy** [comment]
"The M123 version now fully supports 64-bit and has scored 135, 18% higher than the system version, which is quite impressive."
