### ISSUE TITLE
Update to Chromium 124

### ISSUE THREAD

**Issue by Emulond** [Alex313031/Thorium-Android#52]
**Is your feature request related to a problem? Please describe.**
Unreasonably and intolerably slow updates!

**Describe the solution you'd like, including relevant patches or source**
You should stop being so slow with these updates. Chromium 124 exists already, but current Thorium is stuck at 122. Not only that it's annoying, but also puts the users in jeopardy of being security vulnerabilities victims.
@Alex313031
**Additional Notes**
—

**Comment by gz83** [comment]
Maintaining a Chromium fork takes a lot of time, in addition, almost all the files within the repo are modified as well as manually updated by Alex alone, please realize this, what we have right now doesn't compare to the browser projects that are driven by the team as well as the company.

Our next update will be to M123 (the latest stable version at the moment)
