### ISSUE TITLE
Android 4.4 and 6.0 not supported

### ISSUE THREAD

**Issue by Thyristor-Chopper** [Alex313031/Thorium-Android#56]
**System Details**
 - OS: Android 4.4.2 and 6.0.1
 - Thorium Version: 123.0.6312.133

**Problem**
Thorium requires/supports only Android 8.0+ so it's not installable/usable in Android 4.4 and 6.0

**Screenshots**
None

**Additional Notes**
None

**Comment by midzer** [comment]
Maximum Chrom* Version for Android 5 is 94 as I found out lately.

**Comment by Thyristor-Chopper** [comment]
Is it possible to add 4.4+ support like Throium for Windows added support for XP and Vista?

**Comment by midzer** [comment]
"Possible" is everything.

This project is maintained by a single developer, @Alex313031 basically. And Thorium focus is not on Android right now.
