### ISSUE TITLE
WebView with ARM64 arch is required

### ISSUE THREAD

**Issue by Emulond** [Alex313031/Thorium-Android#7]
**System Details**
 - OS: [Android 13, OneUI 5.1]
 - Thorium Version [M116.0.5845.169 - 2nd Release]

**Problem**
Many applications crash and do not detect Thorium WebView in spite of being enabled in Developer Settings and installed in **/system/app/** directory. It is caused by the fact you do not produce Arm64 builds specifically for the WebView integration.

**Screenshots**
Are not required.

**Additional Notes**
Here is a piece of a crashlog of Telegram X:
```
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/system/app/ThoriumWebView/ThoriumWebView.apk!/lib/armeabi-v7a/libwebviewchromium.so" is 32-bit instead of 64-bit
```

**Comment by Alex313031** [comment]
@Emulond You are right. Until relatively recently, it was only possible to compile the arm32 version of the webview, and arm32 and arm64 Android versions both used the arm32 version. Now, however, they fixed it and you can make arm64 versions.

Thanks for bringing this to my attention. Next Android release (coming tomorrow or next few days) will have both versions.
