### ISSUE TITLE
App crashes when pushing the back button 

### ISSUE THREAD

**Issue by wallentx** [Alex313031/Thorium-Android#8]
**System Details**
 - OS: Android 14 - U1B1.230908.003
 - Thorium Version: 116.0.5845.184

**Problem**
Pushing the Android back button soft key to navigate back to a previous page causes Thorium to close, and sometimes crash. This has persisted on all versions of Android 14.
I've never been able to navigate to a previous page.

**Comment by greysonofusa** [comment]
Same issue here Pixel 7 running Android 14.

**Comment by gz83** [comment]
Does Chrome work on your phone?

**Comment by greysonofusa** [comment]
Yes, chrome works on my phone.

**Comment by Thetechoftacos** [comment]
It's fixed on the latest update.
