### ISSUE TITLE
APP does not maximize the window

### ISSUE THREAD

**Issue by brguerra77** [Alex313031/Thorium-Android#9]
**System Details**
 - Android 11 , Lenovo Tablet

**Problem**
When opening the browser window the maximize window icon does not show, or better, it is shaded.

**Comment by gz83** [comment]
Does Chrome do the same thing on your tablet?

@brguerra77

**Comment by brguerra77** [comment]
Hello ,

I've only used Brave browser on this tablet, so can't really say what's
Chrome behaviour. I can try it and advise back.

Thanks.

**Comment by brguerra77** [comment]
Hello,

I can confirm that on Chrome browser, the maximize window icon is active,
so i can use the full tablet screen. This icon on Thorium is shaded grey,
like it's not active.

Let me know if you need more details.

Maybe the Android version of the browser is more toward phone than tablets,
if that's the case then i apologize.

Thank you.

A quarta, 18/10/2023, 03:41, Bruno Guerra ***@***.***> escreveu:

> Hello ,
>
> I've only used Brave browser on this tablet, so can't really say what's
> Chrome behaviour. I can try it and advise back.
>
> Thanks.
>
> Sent from my Oppo Find X5 Pro
>

**Comment by gz83** [comment]
Sorry for the bad experience, we may not have handled Thorium correctly under tablets, or there may be specific configurations of Chrome that are not publicly available that make Chrome work properly on tablets.

@brguerra77

**Comment by brguerra77** [comment]
no need to be sorry Ho , i will definitely try Thorium when i get my laptop.

In case there's any improvement for the tablet usage or if any test is
needed let me know, i'll be more than happy to support.

Thank you.

A quarta, 18/10/2023, 14:08, Ho Cheung ***@***.***> escreveu:
